// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cytgvilabwrbedtvyajb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dGd2aWxhYndyYmVkdHZ5YWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTIyODcsImV4cCI6MjA3NzMyODI4N30.O_2aELLW-eiw46AoguGz0XWm8w4hEHI7BPQMQL4eFHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});